apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lbs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-lbs
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Release.Name }}-lbs
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-lbs
    spec:
      securityContext:
        runAsUser: 2001
        runAsGroup: 2001
      containers:
        - name: lbs
          image: {{ .Values.images.lbs }}
          env:
          - name: TZ
            value: Etc/UTC
          - name: LABEL_STUDIO_HOST
            value: https://{{ .Values.ingress.host }}
          - name: LABEL_STUDIO_PROXY
            value: "true"
          - name: CSRF_TRUSTED_ORIGINS
            value: https://{{ .Values.ingress.host }}
          - name: LABEL_STUDIO_USERNAME
            value: default_user@localhost
          - name: LABEL_STUDIO_PASSWORD
            value: default_user@localhost
          - name: LABEL_STUDIO_USER_TOKEN
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6ODA3MTU1MDYwOCwiaWF0IjoxNzY0MzUwNjA4LCJqdGkiOiI3YjkzNjNjNTNjMDU0NDhkODQ2NTNkNGRiMDllZjk0YyIsInVzZXJfaWQiOiIxIn0.M_0Gv3mMVI5pW3y73_IxtZBAVfHLNrQmkEsmbrdj1zE
          command:
            - /venv/bin/label-studio
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8080
          livenessProbe:
            periodSeconds: 60
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /
              port: 8080
      restartPolicy: Always
