apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lbs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-lbs
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Release.Name }}-lbs
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-lbs
    spec:
      securityContext:
        runAsUser: 2001
        runAsGroup: 2001
      containers:
        - name: lbs
          image: {{ .Values.images.lbs }}
          env:
          - name: TZ
            value: Etc/UTC
          command:
            - /venv/bin/label-studio
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8080
          livenessProbe:
            periodSeconds: 60
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /
              port: 8080
      restartPolicy: Always
