apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lbs
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-lbs
  ports:
    - name: "lbs-port"
      port: 8080
      protocol: TCP
