images:
  codeserver: t-ctr.otvl.org/code-server-base:4.105.1-define-it
  cs_ops: t-ctr.otvl.org/cs-ops:0.0.1
  traefik: traefik:v3.4
nvidia: false
resources:
  requests:
    cpu: "2"
    memory: 1Gi
host_aliases:
  # hostAliases:
  # - ip: "172.25.0.7"
  #   hostnames:
  #   - t-sk3s-sv-loc
ingress:
  enabled: true
  # host: otvl-ctr.example.com, defaults to <release-name>.example.com
user: cs-user
apr_password: "$apr1$eh5iCNFs$VsvLPBjU0fkP.0ZURuZjo1"
sync_server: sync-server
node_label: otvl-agent-value
dns_resolv_content:
kubeconfig:
spubk:
sprik:
