apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dv
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-dv
  ports:
    - name: "dv-port"
      port: 3000
      protocol: TCP
