apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-th
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-th
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Release.Name }}-th
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-th
    spec:
{{- if .Values.nvidia }}
      runtimeClassName: nvidia
{{- end }}
      securityContext:
        runAsUser: 2001
        runAsGroup: 2001
{{- if .Values.host_aliases }}
      {{ toYaml .Values.host_aliases | nindent 6 }}
{{- end }}
      initContainers:
        - name: setup-htdl
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          image: {{ .Values.images.cs_ops }}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/cs_ops.sh
            - setup
            - all
          volumeMounts:
          - mountPath: /home/th-user
            name: home-volume
          - mountPath: /tools
            name: tools-volume
          - mountPath: /data
            name: data-volume
          - mountPath: /local
            name: ephemeral-volume
        - name: restore-all
          image: {{ .Values.images.cs_ops }}
          imagePullPolicy: IfNotPresent
          env:
          - name: SYNC_SERVER
            value: {{ .Values.sync_server }}
          - name: SYNC_USER
            value: {{ .Values.user }}
          command:
            - /usr/local/bin/tini
            - --
            - /usr/local/bin/cs_ops.sh
            - restore
            - all
          volumeMounts:
          - mountPath: /home/th-user
            name: home-volume
          - mountPath: /tools
            name: tools-volume
          - mountPath: /data
            name: data-volume
          - mountPath: /configmap
            name: th-config-volume
        - name: init-dev-env
          image: {{ .Values.images.theia }}
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: Etc/UTC
          - name: XDG_CACHE_HOME
            value: /local/cache
          - name: SYNC_SERVER
            value: {{ .Values.sync_server }}
          - name: SYNC_USER
            value: {{ .Values.user }}
          - name: HAS_NVIDIA
            value: {{ quote .Values.nvidia }}
          command:
            - /usr/local/bin/tini
            - --
            - /usr/local/bin/init_dev_env.sh
          volumeMounts:
          - mountPath: /home/th-user
            name: home-volume
          - mountPath: /tools
            name: tools-volume
          - mountPath: /data
            name: data-volume
          - mountPath: /local
            name: ephemeral-volume
          - mountPath: /configmap
            name: th-config-volume
      containers:
        - name: code-server
          image: {{ .Values.images.theia }}
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: Etc/UTC
          - name: XDG_CACHE_HOME
            value: /local/cache
          - name: TMPDIR
            value: /local/tmp
          - name: SYNC_SERVER
            value: {{ .Values.sync_server }}
          - name: SYNC_USER
            value: {{ .Values.user }}
          - name: HAS_NVIDIA
            value: {{ quote .Values.nvidia }}
{{- if .Values.kubeconfig }}
          - name: KUBECONFIG
            value: /etc/kubeconfig.yml
{{- end }}
          command:
            - /usr/local/bin/tini
            - --
            - /usr/local/bin/entrypoint.sh
            - node
            - /home/theia/examples/browser/lib/backend/main.js
            - --hostname=0.0.0.0
          volumeMounts:
          - mountPath: /home/th-user
            name: home-volume
          - mountPath: /tools
            name: tools-volume
          - mountPath: /data
            name: data-volume
          - mountPath: /local
            name: ephemeral-volume
          - mountPath: /configmap
            name: th-config-volume
{{- if .Values.dns_resolv_content }}
          - mountPath: /etc/resolv.conf
            name: resolv-config-volume
            subPath: resolv.conf
{{- end }}
{{- if .Values.kubeconfig }}
          - mountPath: /etc/kubeconfig.yml
            name: kubeconfig-config-volume
            subPath: kubeconfig.yml
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 3000
          livenessProbe:
            periodSeconds: 60
            timeoutSeconds: 2
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            periodSeconds: 60
            timeoutSeconds: 2
            httpGet:
              path: /
              port: 3000
{{- if .Values.node_label }}
      nodeSelector:
        "otvl-agent": {{ .Values.node_label }}
{{- end }}
      volumes:
      - name: home-volume
        emptyDir:
      - name: tools-volume
        emptyDir:
      - name: data-volume
        emptyDir:
      - name: ephemeral-volume
        emptyDir:
      - name: th-config-volume
        configMap:
          name: {{ .Release.Name }}-th-cmap
{{- if .Values.dns_resolv_content }}
      - name: resolv-config-volume
        configMap:
          name: {{ .Release.Name }}-resolv-cmap
          items:
          - key: resolv.conf
            path: resolv.conf
{{- end }}
{{- if .Values.kubeconfig }}
      - name: kubeconfig-config-volume
        configMap:
          name: {{ .Release.Name }}-kubeconfig-cmap
          items:
          - key: kubeconfig.yml
            path: kubeconfig.yml
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
{{- end }}
