apiVersion: v1
kind: Secret
metadata:
  name: ds-pods-secrets
data:
  postgres_passwd: {{ cv.dv_secrets.postgres_passwd | b64encode }}
  aws_access_key_id: {{ cv.dv_secrets.aws_access_key_id | b64encode }}
  aws_secret_access_key: {{ cv.dv_secrets.aws_secret_access_key | b64encode }}    
