images:
  dv_ide: t-ctr.otvl.org/dv-ide:1.66.2-p1-tbd
  dv_ops: t-ctr.otvl.org/dv-ops:1.0.0-tbd
  traefik: traefik:v3.4
nvidia: false
resources:
  requests:
    cpu: "2"
    memory: 1Gi
host_aliases:
  # hostAliases:
  # - ip: "172.25.0.7"
  #   hostnames:
  #   - t-sk3s-sv-loc
ingress:
  enabled: true
  # host: otvl-ctr.example.com, defaults to <release-name>.example.com
user: dv-user
apr_password: "$apr1$eh5iCNFs$VsvLPBjU0fkP.0ZURuZjo1"
sync_server: sync-server
node_label: otvl-agent-value
dns_resolv_content:
kubeconfig:
spubk:
sprik:
